### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#102]
> issue [3] Bot stopped logging user joins. Last Join was on 12/29/2020, After Morgan joined. it Only showing User leaves.

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/794411143975141377) by *meankitty#7836* on Firekitten Gaming

**Comment by Dav-Git** [comment]
Contacted the lady who made it. Let's see.

**Comment by DannoEdits** [comment]
Issue has been fixed.  Found that an unset Custom URL caused the issue of not logging joins.  Once set, it fixed itself.  Dav - reopen if I misclosed the issue.
