### ISSUE TITLE
Claw not working

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#104]
>  the bug command is for some reason failing, it still applies the mute role however does not create the channel and spits out the usual error.

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/799070731333926953) by *Jack N#7203* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Running the command returns

> Error in command 'claw'. Check your console or logs for details.

Check around 0020 UTC.

**Comment by Dav-Git** [comment]
I'm implementing a temporary solution here. This will need to get changed with the next dpy bump to 1.6 See #105
