### ISSUE TITLE
Change Ping Safe Role Name

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#110]
> Change Ping Safe Staff to PSS and Ping Safe Admin to PSA to avoid people from thinking they can ping staff because of the Ping Safe role.

Feature [requested](https://discord.com/channels/332834024831582210/469036337580998658/802612208253141044) by *Daniel_Edits#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
$ and & respectfully
