### ISSUE TITLE
Better birthdays 🎉

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#112]
>  move birthday role above KC and CR and disable the "hoisted" setting.

Feature [requested](https://discord.com/channels/332834024831582210/360478963115491328/804351260932309022) by *Dav#6998* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Thoughts on giving them some birthday perms to promote people actually getting the birthday role?
Maybe add link embeds for people who aren't yet BB+ or maybe a custom command or two?

**Comment by Dav-Git** [comment]
I'm against this. Imo the only purpose of bday role should be to highlight those that want it.

**Comment by DannoEdits** [comment]
Closing as it was deemed negative by other admins.
