### ISSUE TITLE
Fix muted role

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#115]
>  When staff is muted it kinda borks up and actually mutes them in public channels but not in staff.  Though this really shouldn't be an issue since they SHOULDN'T BE GETTING MUTED in the fist place!

Bug [reported](https://discord.com/channels/332834024831582210/465639800406278146/809200576855932969) by *Daniel_Edits#5297* on Firekitten Gaming

**Comment by Dav-Git** [comment]
yo <@269854496056672258> this is yours

**Comment by DannoEdits** [comment]
> yo <@269854496056672258> this is yours

bruh... it's in my project

**Comment by DannoEdits** [comment]
This is absolutely pointless because staff shouldn't be getting muted in the first place. If I do a perms rework at some point maybe I'll implement a fix, but it's not worth my time to fix this issue. And I mean, if you get muted, it's your own dang fault so quite complaining.
