### ISSUE TITLE
Antiraid Fix thing

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#118]
Type = no

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/812092001104297994) by *Atikah#8384* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Antiraid type = no in channels - is it?  Verify.
Remove type perms from YTM and NB in their channels if still can type.

**Comment by DannoEdits** [comment]
Antiraid wasn't set for YTM and NB, set perms for it.  Removed type but they can still see those channels because of Discord hierarchy (or well, lack thereof).
