### ISSUE TITLE
Antiraid

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#128]
>  Give antiraid perms back to see other channels besides just <#823647577512869918> once this situation passes.

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/825751790355087381) by *Daniel_Edits#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Issue seems to have subsided, please restore

**Comment by DannoEdits** [comment]
Restored rules, rp info, and faqs to antiraid
