### ISSUE TITLE
fork invoice

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#130]
>  Maintain a custom fork of invoice to get rid of that muting nonsense

Enhancement [suggested](https://discord.com/channels/332834024831582210/360478963115491328/828662275623616582) by *Dav#6998* on Firekitten Gaming

**Comment by Dav-Git** [comment]
Is this still relevant? Afaik people this somewhat fixed itself?

**Comment by DannoEdits** [comment]
This was because if you joined a no mic while your mic was muted (locally), you would not be able to type. Essentially making it useless.

**Comment by Dav-Git** [comment]
non issue
