### ISSUE TITLE
Clone channels

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#135]
>  User reported that while in a private vc they tried to rename channel and we instead shown a “clone channel” option. Needs investigation into what that is and who can use it (perms side) - ref dm log

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/843324859593654283) by *Daniel_Edits#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Moving to Dav side. Channel creation and running `-vc hidden` give the user Manage Channel permissions which doesn't allow for cloning channel (because of server perms) but they can delete.

**Comment by Dav-Git** [comment]
This has been fixed and adressed with GHSA-3f73-8j6q-28v8
