### ISSUE TITLE
Make Text RP Great Again

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#146]
>  change it so each RP is its own thread

Feature [requested](https://discord.com/channels/332834024831582210/469036337580998658/885207365807407215) by *Jack N.#7203* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Complete. Will keep this issue open until I see current role plays have been moved and old text-rp channel archived or deleted.

**Comment by DannoEdits** [comment]
Channel closed from visibility.
