### ISSUE TITLE
Revoke send permission for cow'ed in thread channels

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#147]
>  On any channel with the ability to create threads, revoke the "Send Messages in Threads" permission from the Cow'ed role.

Feature [requested](https://discord.com/channels/332834024831582210/469036337580998658/888765689169596457) by *Daniel_Edits#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Also make it where they can't make a new thread

**Comment by DannoEdits** [comment]
In theory, if they can't send messages in threads, they can't start...soooo....done
