### ISSUE TITLE
Danno check rule perm

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#150]
> Happy now :P

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/893082664209367050) by *Atikah#8384* on Firekitten Gaming

**Comment by DannoEdits** [comment]
When I went to look at the rules perms, all was in order. No one was set as an override. Running theory was previously that this occurred on failed claws - will run some tests and see if I can replicate.

**Comment by DannoEdits** [comment]
This was due to failed claw returns, fixed with FK#155
