### ISSUE TITLE
Perms overhaul for Staff

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#152]
> Adjust the staff perms to reflect the new 'Staff' role and work at removing the perms difference for CR and KC (ie using just the Staff role and not these roles). Also also, fix the staff muting thing so staff can't get muted (even though this SHOULDN'T BE AN ISSUE but for some reason it is :/)

Enhancement [suggested](https://discord.com/channels/332834024831582210/469036337580998658/893989946891845642) by *Daniel_Edits#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Depreciated permissions skew.
