### ISSUE TITLE
move contacts location in sidebar

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#157]
> Hello, currently the location of contact- channels is in the Ask category, which is at the bottom of the server and i have to scroll past everything to get to it. Can dan and you move them up in to either Staff-Area or their own channel up higher. thanks. dan said to do this

Feature [requested](https://discord.com/channels/332834024831582210/469036337580998658/919713772359262208) by *bozo88#9967* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Created category, need to do perms then toss over to Dav for the channel creation aspect.

**Comment by DannoEdits** [comment]
Perms should be complete. Tossing to Dav for bot end, then will test.
