### ISSUE TITLE
FAQ update

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#160]
>  Danno need to update FAQ cause it still has CR role

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/927948753837625454) by *Atikah#8384* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Removed CR and added Birthday; still needs to be put into channel, will do early AM on Jan 5 (CST) as channel needs to be closed.

**Comment by DannoEdits** [comment]
Le updated
