### ISSUE TITLE
wrong grammar

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#163]
>  For automutes, the wrong grammar is used
> 
> "Server mute
> To many warnings(5)."
> 
> should be too, not to.

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/933753073027915896) by *Jack N.#7203* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Is this Red sided or is this something that @Dav-Git can do?

**Comment by Dav-Git** [comment]
It is someting @Dav-Git can do. However he does decide that it's a 80% of the effort 20% of the benefit situation.
