### ISSUE TITLE
Text rp thread

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#167]
>  It looks like people can't create a new thread. Confirm with an alt

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/938099192260354088) by *Atikah#8384* on Firekitten Gaming

**Comment by DannoEdits** [comment]
TRP role now has access to create threads in text-rp. Public and private threads are enabled. Verified the contact role cannot see and the cow'ed role cannot create (though because discord permissions are dumb sometimes they will still be able to...DISCORD!!!!)
