### ISSUE TITLE
Fun Room is borked yet a friggin gain

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#170]
>  Dav, plz fix. Fun rooms can be created but not auto deleted, I don't know whyyyyyy <3 Dan

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/940787771860193301) by *Danno#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Uuuh nevermind, it's not just fun room, it's private vc's too....
