### ISSUE TITLE
Why u take my shit

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#171]
>  People are getting confused, I vaguely remember us having a section in the rules embed clarifying that certain channels have extra rules located in pins. Where'd this go?
> 
> Further, its weird that

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/948319252077740082) by *Jack N.#7203* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Check the footer. You're turning into the people we are annoyed about that don't read.
