### ISSUE TITLE
Rules clarification

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#177]
> All punishments are held to the account itself, even if the person who broke the rule is not the account's owner. Furthermore, mutes, bans and restrictions will be held against known alternate accounts on top of the initial account.

Enhancement [suggested](https://discord.com/channels/332834024831582210/469036337580998658/960158293714681890) by *Danno#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Awaiting admin approval before push

**Comment by DannoEdits** [comment]
Approved and pushed
