### ISSUE TITLE
dankmemer broke

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#178]
>  Dankmemer plugin is broken? it causes the bot to think for a while and then spits out a error message to check logs.

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/966538344865620018) by *meankitty#7836* on Firekitten Gaming

**Comment by Dav-Git** [comment]
I hate you kev <3 This was a fucking pain in the ass. Guvicorn, Imgen and Flare... get your fucking documentation in order. init.d sucks. Use Systemd instead. I'm going to sleep now. Peace out.
