### ISSUE TITLE
Scenario Add

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#179]
> Add a clause noting that scenarios for law enforcement characters are not used because they only react to envuironment around them, they are not causing scenarios

Enhancement [suggested](https://discord.com/channels/332834024831582210/469036337580998658/969549957700935720) by *Danno#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Added. Could not remember decision on Rule 1 since the ARP rule change, so I have left it. If that should be modified, please new enhancement request with new wording.
