### ISSUE TITLE
VC Text Channels

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#181]
> Enable and test the permissions and setups for the vc text channels (community elements). Once done, push an announcement with explanation of what is going to be happening - planned full removal by June 29 (their forced implimentation)

Enhancement [suggested](https://discord.com/channels/332834024831582210/469036337580998658/982251028181303316) by *Danno#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Enabled across the server, permissions are set to default. Need to adjust on a per role basis. Also will be enabling activities as I am doing this. Unsure of timeline, hopefully overall is done by the weekend but finished might be closer to the 12th if not later.

**Comment by DannoEdits** [comment]
I am going to kill this request. I think most people still use the classic text channels. We can revisit removing if they become inept.
