### ISSUE TITLE
Rules command

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#184]
>  Create a command that will send the user the rules if they are having issues seeing them. (Dan might try to do the coding and have Dav check and merge)

Feature [requested](https://discord.com/channels/332834024831582210/469036337580998658/1031940036553347153) by *Danno#5297* on Firekitten Gaming

**Comment by Dav-Git** [comment]
Daaaaan! When will you make?

**Comment by DannoEdits** [comment]
There @Dav-Git, I sent'ed it! (I no remember how to create pull request...)
