### ISSUE TITLE
trains channel

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#186]
> as per boss lady, monty and the stream chat request, we need to set up a train channel

Feature [requested](https://discord.com/channels/332834024831582210/469036337580998658/1080992511679537234) by *Atikah#8384* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Perms side done. Bumping to Dav for bot side

**Comment by DannoEdits** [comment]
I was nice and did the bot side. Just edit your message plz kthx :)
