### ISSUE TITLE
Soundboard

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#189]
>  Enable for masses, allow boosters and members to use external sounds. Create new role for no soundboard access. Punt to dav for bot magic once done

Feature [requested](https://discord.com/channels/332834024831582210/469036337580998658/1099690406125523095) by *Danno#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Soundboard enabled for the server, Boosters and Members (and retired staff) all have ability to use sounds from external servers. NSB role created and has category master for general.

Dav: Please set Fun Room channel generation to DENY the "Use Soundboard" permission to role "1069294686243651665". I have set both the General category master, as well as the default Fun Room channel to reflect this permission change.
Also, this is not an immediate thing, but at some point, we should have a command that staff and higher can use to add this role, similar to the -nsp command.

**Comment by DannoEdits** [comment]
Nearly 1 year update, this fixed itself. Dav is doing command now.
