### ISSUE TITLE
Come, mister tally man, tally me a commannd

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#192]
>  Daylight come and me wan' go home. Come, Mister tally man can you add a command which restricts the ability to speak in ask channels and seperate it fully from NSS. Daylight come and me wan' go home.

Feature [requested](https://discord.com/channels/332834024831582210/469036337580998658/1108559278379376721) by *Jack N.#7203* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Translation: NSS affect scenario. New NAC role to revoke all ask channels. Reflect changes across.

**Comment by Dav-Git** [comment]
On hold pending #admin-chat discussion.

**Comment by Dav-Git** [comment]
After further discussion this will not be required.
