### ISSUE TITLE
Move bot permissions from KC to Staff roles

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#195]
> As the CR role is now dead, we no longer need to have bot permissions separated on a role basis for staff members. Please transittion permissions from KC to Staff (view admin for Role IDs if needed).

Enhancement [suggested](https://discord.com/channels/332834024831582210/469036337580998658/1115241127197560892) by *Danno#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Migrating to 213 as part of a master overhaul of permissions.
