### ISSUE TITLE
Update moderation

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#200]
> Add the “bd” command into the moderation embed

Enhancement [suggested](https://discord.com/channels/332834024831582210/469036337580998658/1124455636147634318) by *dan.no#0* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Code updated and committed, not wanting to take on bot end..

**Comment by DannoEdits** [comment]
I hate my life... I reloaded but no update... me is a dum...
