### ISSUE TITLE
Broken joinflag and leveler command

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#201]
> Join flag no longer work, please fix. Also the leveler/rank command

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/1133266002092757043) by *atikah_#0* on Firekitten Gaming

**Comment by Dav-Git** [comment]
Migrate to vert‘s leveler. Has data import from the current one.

**Comment by DannoEdits** [comment]
Leveler is being deprecated. Will test join flags to see if this issue is still applicable.

**Comment by DannoEdits** [comment]
Join flags seem to work just fine at the moment. (Only appear in join-leave). Closing issue, please reopen if broken again.
