### ISSUE TITLE
Claw and remove once left

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#202]
>  In short, if a user is clawwed and they leave the server and rejoin, they will only be able to see the rules channel. It will not make a new contact channel (I swear we did this at one point), nor will it notify them or anything. Also ~~not sure if this is a tester issue (need someone with a "clean" account for additional testing) but~~ it takes roughly 45 seconds for a claw channel to be made or to link the user back to it if they rejoin while still in a claw channel.
> https://canary.discord.com/channels/332834024831582210/339741123406725121/1139954609415274536
> https://canary.discord.com/channels/332834024831582210/1139970758592970852

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/1139974503968014428) by *dan.no#0* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Confirmed with a clean account, claw takes ~45 seconds in order to create or release. That seems kinda high.

**Comment by Dav-Git** [comment]
Discord ratelimits makes this slow. Go complain over there
