### ISSUE TITLE
Temp staff role

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#208]
> Base level perms and visibility. Needs new color assignment (bleh). Ref admin for details.

Enhancement [suggested](https://discord.com/channels/332834024831582210/469036337580998658/1171455126104453180) by *dan.no* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Add access to warning and muting

**Comment by DannoEdits** [comment]
I didn't break it and it should work as intended... sorry Dav if I broke anything...
