### ISSUE TITLE
Antiembed stuffz

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#213]
> Make role to no embed server wide

Feature [requested](https://discord.com/channels/332834024831582210/360478963115491328/1221156685087772802) by *dan.no* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Role created, bringing @Dav-Git into this at this point for the command to be created (admin only?), while I work on the permissions side.

Current user activity roles will remain until these changes have been made (minimum permissions fixed). Once done, admins shall discuss deprecating the existing activity roles or if one (or both) should be kept and just remove members from lists.

**Comment by DannoEdits** [comment]
Bringing #195 into this and updating permissions server wide for KC, CR, Staff, and NEM. (As well as verifying existing perms still in place and functional).

**Comment by DannoEdits** [comment]
Additional note: `self-promotion` will also need a rework in permissions due to the fact that the member roles being deprecated. NEM should block that as well (still allow post, just not embed or upload). NEM should also revoke upload permissions across all channels for YT mem and boosters that abuse.

**Comment by DannoEdits** [comment]
Staff channels (including live stream) and higher are done. Need to do all public channels and lower.

**Comment by DannoEdits** [comment]
All permissions are done, roles are deleted, updated, or likewise changed. FAQs have been updated to reflect these new changes.

**FINALLY DONE WITH THIS BECAUSE @Dav-Git HATES ME AND KILLED LEVELER**
