### ISSUE TITLE
Make MH Great Again

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#214]
>  pls fix mental health command, changing it to the discussed resources in <#360478963115491328>

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/1221187653630824500) by *jackinthebox_* on Firekitten Gaming

**Comment by DannoEdits** [comment]
It's done, now shhhhhhh. I just wanted to finish the season first... JACK
