### ISSUE TITLE
FAQ Update (Server)

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#216]
> Remove things regarding leveling (Catnip and Furballs) once gone. Also, SPA is no longer a live roll, change to state "Why do I have a random no color role?"

Enhancement [suggested](https://discord.com/channels/332834024831582210/469036337580998658/1228669553303883786) by *dan.no* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Embed is updated to current (unless we find more things to add between now and going live). Need to wait to go live until I finish permissions overhaul and remove current member roles.
