### ISSUE TITLE
NSB should disable sounndboard access in vc creation

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#217]
> The NSB role (1069294686243651665) is added to the vc by the general category permissions but it is not disabled during vc duplication process.

Enhancement [suggested](https://discord.com/channels/332834024831582210/469036337580998658/1229042466100084766) by *dan.no* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Apparently changing the permission on the master vc channel fixed this issue. /shrug
