### ISSUE TITLE
Moderation Update

### ISSUE THREAD

**Issue by FireKitten-Staff** [Dav-Git/fk-cogs#218]
> Once Dav has new command for punishment roles created and established, update existing modshort and modfull commands to include resource. Will update with command info as available.

Enhancement [suggested](https://discord.com/channels/332834024831582210/469036337580998658/1230214362359271434) by *dan.no* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Hehe, this be donezo

<iframe src="https://giphy.com/embed/RMeag0pzYAaZSkBSWA" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/RMeag0pzYAaZSkBSWA">via GIPHY</a></p>
