### ISSUE TITLE
Not allow role assignment of "Fun Room" if cow role is applied

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#52]
Submitted by: Dan
As we discussed in vc, if a member has the cow role, they do not receive a fun room role to type in no mic

**Comment by Dav-Git** [comment]
Not possible with the current setup. Maybe a future project

**Comment by Dav-Git** [comment]
<@269854496056672258> can you confirm if this is still an issue?

**Comment by DannoEdits** [comment]
This is no longer an issue and can be closed.
