### ISSUE TITLE
Fun Room No Mic

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#76]
>  First fun room doesn’t have no mic channel

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/773164359362936853) by *Atikah#8384* on Firekitten Gaming

**Comment by Dav-Git** [comment]
Is this still a problem?

**Comment by DannoEdits** [comment]
Yes.  Joining first fun room doesn't move you to the fun room created for the no mic channel, you have to move yourself.  However, a no mic channel is created, no one is assigned the role.
