### ISSUE TITLE
Private VC's cannot view streams

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#81]
>  Users who join a private VC cannot see streams from other members in the stream because they cannot see the channel (permission wise).  Could we add the channel role to the vc which would allow them to see that channel since it removes the role once they leave the channel anyways?

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/779154769003806791) by *Daniel_Edits#5297* on Firekitten Gaming

**Comment by Dav-Git** [comment]
I still don't quite grasp what the issue is here. Can someone who actually unerstands perms (e.g. @DannoEdits or anyone else who does) tell me what needes to be changed?

**Comment by DannoEdits** [comment]
@Dav-Git When the VC is hidden, the role created to allow the no mic channel needs to be added to the VC and given "See Channel" perm to green.
![image](https://user-images.githubusercontent.com/74838316/100804724-faeefa80-33f2-11eb-93d9-77f0fde1a3d9.png)
![image](https://user-images.githubusercontent.com/74838316/100804771-09d5ad00-33f3-11eb-87b1-f6ef70f3a48a.png)

Hope that explains it.
