### ISSUE TITLE
Adding join command to <#779118031385133126>

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#83]
>  Add in how to join a private vc with a command if someone just sends the code so they are able to know what they need to type in order to join successfully into the explanation in <#779118031385133126>

Feature [requested](https://discord.com/channels/332834024831582210/469036337580998658/779813811133743114) by *Daniel_Edits#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Also add that channel names should be ONE word or a STRING in QUOTES (blame Ted)

**Comment by Dav-Git** [comment]
OMFG ted

**Comment by Dav-Git** [comment]
![grafik](https://user-images.githubusercontent.com/57032623/100791572-53cd8b80-3411-11eb-9071-2a84afba429e.png)
This seems to be a non issue. Feel free to re-open if I missed something @DannoEdits
