### ISSUE TITLE
Perms check

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#88]
>  Verify that photos, memes, etc have upload rights, also check if ask channels have cancel embeds, view history for antiraid in all avail channels, check if anyone has message history denied in rules, NSP NCC NSS perms deny correctly

Enhancement [suggested](https://discord.com/channels/332834024831582210/779670362115145738/780772693850849281) by *Daniel_Edits#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Perms have been reviewed, looks like everything is in order.  Also updated a few things to make easier server operation.
