### ISSUE TITLE
DAE not in fun room

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#91]
>  Investigate with Dav why DAE isn't able to see into fun room no mics

Bug [reported](https://discord.com/channels/332834024831582210/779670362115145738/780773406898913291) by *Daniel_Edits#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Things look good on my end, I think it's a bot perms side that needs to assign the override to the no mic channels as created for DAE.

**Comment by Dav-Git** [comment]
@DannoEdits We'd need to have DAE with admin perms to do this.

**Comment by DannoEdits** [comment]
Determined DAE doesn't need admin.  People can just use #music-control
