### ISSUE TITLE
Check self-role perms

### ISSUE THREAD

**Issue by Dav-Git** [Dav-Git/fk-cogs#97]
>  User reacted to message on their own, investigate

Bug [reported](https://discord.com/channels/332834024831582210/469036337580998658/786932452622729237) by *Daniel_Edits#5297* on Firekitten Gaming

**Comment by DannoEdits** [comment]
Should be fixed.  Fireteam + didn't have reacts disabled even though everyone was.  Potential odd bug on Discord end.
